// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ethicalaakash/k8s-automator/internal/kubernetes (interfaces: KubernetesClient,NamespaceInterface,PodInterface,ServiceInterface,EventInterface,DeploymentInterface,HorizontalPodAutoscalerInterface,ScaledObjectInterface)

// Package kubernetes is a generated GoMock package.
package kubernetes

import (
	context "context"
	reflect "reflect"

	common "github.com/ethicalaakash/k8s-automator/internal/common"
	kubernetes "github.com/ethicalaakash/k8s-automator/internal/kubernetes"
	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/kedacore/keda/v2/apis/keda/v1alpha1"
	v1 "k8s.io/api/apps/v1"
	v2 "k8s.io/api/autoscaling/v2"
	v10 "k8s.io/api/core/v1"
	v11 "k8s.io/apimachinery/pkg/apis/meta/v1"
	kubernetes0 "k8s.io/client-go/kubernetes"
	rest "k8s.io/client-go/rest"
)

// MockKubernetesClient is a mock of KubernetesClient interface.
type MockKubernetesClient struct {
	ctrl     *gomock.Controller
	recorder *MockKubernetesClientMockRecorder
}

// MockKubernetesClientMockRecorder is the mock recorder for MockKubernetesClient.
type MockKubernetesClientMockRecorder struct {
	mock *MockKubernetesClient
}

// NewMockKubernetesClient creates a new mock instance.
func NewMockKubernetesClient(ctrl *gomock.Controller) *MockKubernetesClient {
	mock := &MockKubernetesClient{ctrl: ctrl}
	mock.recorder = &MockKubernetesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubernetesClient) EXPECT() *MockKubernetesClientMockRecorder {
	return m.recorder
}

// Deployments mocks base method.
func (m *MockKubernetesClient) Deployments(arg0 string) kubernetes.DeploymentInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deployments", arg0)
	ret0, _ := ret[0].(kubernetes.DeploymentInterface)
	return ret0
}

// Deployments indicates an expected call of Deployments.
func (mr *MockKubernetesClientMockRecorder) Deployments(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deployments", reflect.TypeOf((*MockKubernetesClient)(nil).Deployments), arg0)
}

// Events mocks base method.
func (m *MockKubernetesClient) Events(arg0 string) kubernetes.EventInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", arg0)
	ret0, _ := ret[0].(kubernetes.EventInterface)
	return ret0
}

// Events indicates an expected call of Events.
func (mr *MockKubernetesClientMockRecorder) Events(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockKubernetesClient)(nil).Events), arg0)
}

// GetClientset mocks base method.
func (m *MockKubernetesClient) GetClientset() *kubernetes0.Clientset {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientset")
	ret0, _ := ret[0].(*kubernetes0.Clientset)
	return ret0
}

// GetClientset indicates an expected call of GetClientset.
func (mr *MockKubernetesClientMockRecorder) GetClientset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientset", reflect.TypeOf((*MockKubernetesClient)(nil).GetClientset))
}

// GetClusterInfo mocks base method.
func (m *MockKubernetesClient) GetClusterInfo(arg0 context.Context) (*common.ClusterInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterInfo", arg0)
	ret0, _ := ret[0].(*common.ClusterInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterInfo indicates an expected call of GetClusterInfo.
func (mr *MockKubernetesClientMockRecorder) GetClusterInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterInfo", reflect.TypeOf((*MockKubernetesClient)(nil).GetClusterInfo), arg0)
}

// GetConfig mocks base method.
func (m *MockKubernetesClient) GetConfig() *rest.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(*rest.Config)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockKubernetesClientMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockKubernetesClient)(nil).GetConfig))
}

// HorizontalPodAutoscalers mocks base method.
func (m *MockKubernetesClient) HorizontalPodAutoscalers(arg0 string) kubernetes.HorizontalPodAutoscalerInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HorizontalPodAutoscalers", arg0)
	ret0, _ := ret[0].(kubernetes.HorizontalPodAutoscalerInterface)
	return ret0
}

// HorizontalPodAutoscalers indicates an expected call of HorizontalPodAutoscalers.
func (mr *MockKubernetesClientMockRecorder) HorizontalPodAutoscalers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HorizontalPodAutoscalers", reflect.TypeOf((*MockKubernetesClient)(nil).HorizontalPodAutoscalers), arg0)
}

// Namespaces mocks base method.
func (m *MockKubernetesClient) Namespaces() kubernetes.NamespaceInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Namespaces")
	ret0, _ := ret[0].(kubernetes.NamespaceInterface)
	return ret0
}

// Namespaces indicates an expected call of Namespaces.
func (mr *MockKubernetesClientMockRecorder) Namespaces() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Namespaces", reflect.TypeOf((*MockKubernetesClient)(nil).Namespaces))
}

// Pods mocks base method.
func (m *MockKubernetesClient) Pods(arg0 string) kubernetes.PodInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pods", arg0)
	ret0, _ := ret[0].(kubernetes.PodInterface)
	return ret0
}

// Pods indicates an expected call of Pods.
func (mr *MockKubernetesClientMockRecorder) Pods(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pods", reflect.TypeOf((*MockKubernetesClient)(nil).Pods), arg0)
}

// ScaledObjects mocks base method.
func (m *MockKubernetesClient) ScaledObjects(arg0 string) kubernetes.ScaledObjectInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScaledObjects", arg0)
	ret0, _ := ret[0].(kubernetes.ScaledObjectInterface)
	return ret0
}

// ScaledObjects indicates an expected call of ScaledObjects.
func (mr *MockKubernetesClientMockRecorder) ScaledObjects(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScaledObjects", reflect.TypeOf((*MockKubernetesClient)(nil).ScaledObjects), arg0)
}

// Services mocks base method.
func (m *MockKubernetesClient) Services(arg0 string) kubernetes.ServiceInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Services", arg0)
	ret0, _ := ret[0].(kubernetes.ServiceInterface)
	return ret0
}

// Services indicates an expected call of Services.
func (mr *MockKubernetesClientMockRecorder) Services(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Services", reflect.TypeOf((*MockKubernetesClient)(nil).Services), arg0)
}

// MockNamespaceInterface is a mock of NamespaceInterface interface.
type MockNamespaceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceInterfaceMockRecorder
}

// MockNamespaceInterfaceMockRecorder is the mock recorder for MockNamespaceInterface.
type MockNamespaceInterfaceMockRecorder struct {
	mock *MockNamespaceInterface
}

// NewMockNamespaceInterface creates a new mock instance.
func NewMockNamespaceInterface(ctrl *gomock.Controller) *MockNamespaceInterface {
	mock := &MockNamespaceInterface{ctrl: ctrl}
	mock.recorder = &MockNamespaceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespaceInterface) EXPECT() *MockNamespaceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNamespaceInterface) Create(arg0 context.Context, arg1 *v10.Namespace) (*v10.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*v10.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNamespaceInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNamespaceInterface)(nil).Create), arg0, arg1)
}

// Get mocks base method.
func (m *MockNamespaceInterface) Get(arg0 context.Context, arg1 string) (*v10.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*v10.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNamespaceInterfaceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNamespaceInterface)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockNamespaceInterface) List(arg0 context.Context) (*v10.NamespaceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].(*v10.NamespaceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNamespaceInterfaceMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNamespaceInterface)(nil).List), arg0)
}

// MockPodInterface is a mock of PodInterface interface.
type MockPodInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPodInterfaceMockRecorder
}

// MockPodInterfaceMockRecorder is the mock recorder for MockPodInterface.
type MockPodInterfaceMockRecorder struct {
	mock *MockPodInterface
}

// NewMockPodInterface creates a new mock instance.
func NewMockPodInterface(ctrl *gomock.Controller) *MockPodInterface {
	mock := &MockPodInterface{ctrl: ctrl}
	mock.recorder = &MockPodInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPodInterface) EXPECT() *MockPodInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPodInterface) Get(arg0 context.Context, arg1 string) (*v10.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*v10.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPodInterfaceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPodInterface)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockPodInterface) List(arg0 context.Context, arg1 v11.ListOptions) (*v10.PodList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*v10.PodList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPodInterfaceMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPodInterface)(nil).List), arg0, arg1)
}

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockServiceInterface) Create(arg0 context.Context, arg1 *v10.Service) (*v10.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*v10.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockServiceInterface)(nil).Create), arg0, arg1)
}

// List mocks base method.
func (m *MockServiceInterface) List(arg0 context.Context, arg1 v11.ListOptions) (*v10.ServiceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*v10.ServiceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceInterfaceMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceInterface)(nil).List), arg0, arg1)
}

// MockEventInterface is a mock of EventInterface interface.
type MockEventInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEventInterfaceMockRecorder
}

// MockEventInterfaceMockRecorder is the mock recorder for MockEventInterface.
type MockEventInterfaceMockRecorder struct {
	mock *MockEventInterface
}

// NewMockEventInterface creates a new mock instance.
func NewMockEventInterface(ctrl *gomock.Controller) *MockEventInterface {
	mock := &MockEventInterface{ctrl: ctrl}
	mock.recorder = &MockEventInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventInterface) EXPECT() *MockEventInterfaceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockEventInterface) List(arg0 context.Context, arg1 v11.ListOptions) (*v10.EventList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*v10.EventList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEventInterfaceMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEventInterface)(nil).List), arg0, arg1)
}

// MockDeploymentInterface is a mock of DeploymentInterface interface.
type MockDeploymentInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeploymentInterfaceMockRecorder
}

// MockDeploymentInterfaceMockRecorder is the mock recorder for MockDeploymentInterface.
type MockDeploymentInterfaceMockRecorder struct {
	mock *MockDeploymentInterface
}

// NewMockDeploymentInterface creates a new mock instance.
func NewMockDeploymentInterface(ctrl *gomock.Controller) *MockDeploymentInterface {
	mock := &MockDeploymentInterface{ctrl: ctrl}
	mock.recorder = &MockDeploymentInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeploymentInterface) EXPECT() *MockDeploymentInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDeploymentInterface) Create(arg0 context.Context, arg1 *v1.Deployment) (*v1.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*v1.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDeploymentInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeploymentInterface)(nil).Create), arg0, arg1)
}

// Get mocks base method.
func (m *MockDeploymentInterface) Get(arg0 context.Context, arg1 string) (*v1.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*v1.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDeploymentInterfaceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDeploymentInterface)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockDeploymentInterface) List(arg0 context.Context, arg1 v11.ListOptions) (*v1.DeploymentList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*v1.DeploymentList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDeploymentInterfaceMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDeploymentInterface)(nil).List), arg0, arg1)
}

// MockHorizontalPodAutoscalerInterface is a mock of HorizontalPodAutoscalerInterface interface.
type MockHorizontalPodAutoscalerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHorizontalPodAutoscalerInterfaceMockRecorder
}

// MockHorizontalPodAutoscalerInterfaceMockRecorder is the mock recorder for MockHorizontalPodAutoscalerInterface.
type MockHorizontalPodAutoscalerInterfaceMockRecorder struct {
	mock *MockHorizontalPodAutoscalerInterface
}

// NewMockHorizontalPodAutoscalerInterface creates a new mock instance.
func NewMockHorizontalPodAutoscalerInterface(ctrl *gomock.Controller) *MockHorizontalPodAutoscalerInterface {
	mock := &MockHorizontalPodAutoscalerInterface{ctrl: ctrl}
	mock.recorder = &MockHorizontalPodAutoscalerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHorizontalPodAutoscalerInterface) EXPECT() *MockHorizontalPodAutoscalerInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHorizontalPodAutoscalerInterface) Create(arg0 context.Context, arg1 *v2.HorizontalPodAutoscaler) (*v2.HorizontalPodAutoscaler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*v2.HorizontalPodAutoscaler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockHorizontalPodAutoscalerInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHorizontalPodAutoscalerInterface)(nil).Create), arg0, arg1)
}

// MockScaledObjectInterface is a mock of ScaledObjectInterface interface.
type MockScaledObjectInterface struct {
	ctrl     *gomock.Controller
	recorder *MockScaledObjectInterfaceMockRecorder
}

// MockScaledObjectInterfaceMockRecorder is the mock recorder for MockScaledObjectInterface.
type MockScaledObjectInterfaceMockRecorder struct {
	mock *MockScaledObjectInterface
}

// NewMockScaledObjectInterface creates a new mock instance.
func NewMockScaledObjectInterface(ctrl *gomock.Controller) *MockScaledObjectInterface {
	mock := &MockScaledObjectInterface{ctrl: ctrl}
	mock.recorder = &MockScaledObjectInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScaledObjectInterface) EXPECT() *MockScaledObjectInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScaledObjectInterface) Create(arg0 context.Context, arg1 *v1alpha1.ScaledObject) (*v1alpha1.ScaledObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*v1alpha1.ScaledObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockScaledObjectInterfaceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScaledObjectInterface)(nil).Create), arg0, arg1)
}
