// Code generated by MockGen. DO NOT EDIT.
// Source: internal/health/health.go

// Package mock_health is a generated GoMock package.
package mock_health

import (
	context "context"
	reflect "reflect"

	common "github.com/ethicalaakash/k8s-automator/internal/common"
	gomock "github.com/golang/mock/gomock"
)

// MockHealthMonitor is a mock of HealthMonitor interface.
type MockHealthMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockHealthMonitorMockRecorder
}

// MockHealthMonitorMockRecorder is the mock recorder for MockHealthMonitor.
type MockHealthMonitorMockRecorder struct {
	mock *MockHealthMonitor
}

// NewMockHealthMonitor creates a new mock instance.
func NewMockHealthMonitor(ctrl *gomock.Controller) *MockHealthMonitor {
	mock := &MockHealthMonitor{ctrl: ctrl}
	mock.recorder = &MockHealthMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthMonitor) EXPECT() *MockHealthMonitorMockRecorder {
	return m.recorder
}

// GetDeploymentStatus mocks base method.
func (m *MockHealthMonitor) GetDeploymentStatus(ctx context.Context, namespace, name string) (*common.DeploymentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeploymentStatus", ctx, namespace, name)
	ret0, _ := ret[0].(*common.DeploymentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeploymentStatus indicates an expected call of GetDeploymentStatus.
func (mr *MockHealthMonitorMockRecorder) GetDeploymentStatus(ctx, namespace, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeploymentStatus", reflect.TypeOf((*MockHealthMonitor)(nil).GetDeploymentStatus), ctx, namespace, name)
}
