// Code generated by MockGen. DO NOT EDIT.
// Source: internal/deployment/deployment.go

// Package mock_deployment is a generated GoMock package.
package mock_deployment

import (
	context "context"
	reflect "reflect"

	common "github.com/ethicalaakash/k8s-automator/internal/common"
	gomock "github.com/golang/mock/gomock"
)

// MockDeploymentManager is a mock of DeploymentManager interface.
type MockDeploymentManager struct {
	ctrl     *gomock.Controller
	recorder *MockDeploymentManagerMockRecorder
}

// MockDeploymentManagerMockRecorder is the mock recorder for MockDeploymentManager.
type MockDeploymentManagerMockRecorder struct {
	mock *MockDeploymentManager
}

// NewMockDeploymentManager creates a new mock instance.
func NewMockDeploymentManager(ctrl *gomock.Controller) *MockDeploymentManager {
	mock := &MockDeploymentManager{ctrl: ctrl}
	mock.recorder = &MockDeploymentManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeploymentManager) EXPECT() *MockDeploymentManagerMockRecorder {
	return m.recorder
}

// CreateDeployment mocks base method.
func (m *MockDeploymentManager) CreateDeployment(ctx context.Context, config *common.DeploymentConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeployment", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDeployment indicates an expected call of CreateDeployment.
func (mr *MockDeploymentManagerMockRecorder) CreateDeployment(ctx, config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeployment", reflect.TypeOf((*MockDeploymentManager)(nil).CreateDeployment), ctx, config)
}
