// Code generated by MockGen. DO NOT EDIT.
// Source: internal/installer/installer.go

// Package mock_installer is a generated GoMock package.
package mock_installer

import (
	context "context"
	reflect "reflect"

	common "github.com/ethicalaakash/k8s-automator/internal/common"
	gomock "github.com/golang/mock/gomock"
)

// MockToolInstaller is a mock of ToolInstaller interface.
type MockToolInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockToolInstallerMockRecorder
}

// MockToolInstallerMockRecorder is the mock recorder for MockToolInstaller.
type MockToolInstallerMockRecorder struct {
	mock *MockToolInstaller
}

// NewMockToolInstaller creates a new mock instance.
func NewMockToolInstaller(ctrl *gomock.Controller) *MockToolInstaller {
	mock := &MockToolInstaller{ctrl: ctrl}
	mock.recorder = &MockToolInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolInstaller) EXPECT() *MockToolInstallerMockRecorder {
	return m.recorder
}

// InstallHelmIfNotPresent mocks base method.
func (m *MockToolInstaller) InstallHelmIfNotPresent() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallHelmIfNotPresent")
	ret0, _ := ret[0].(error)
	return ret0
}

// InstallHelmIfNotPresent indicates an expected call of InstallHelmIfNotPresent.
func (mr *MockToolInstallerMockRecorder) InstallHelmIfNotPresent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallHelmIfNotPresent", reflect.TypeOf((*MockToolInstaller)(nil).InstallHelmIfNotPresent))
}

// InstallKEDA mocks base method.
func (m *MockToolInstaller) InstallKEDA(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallKEDA", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstallKEDA indicates an expected call of InstallKEDA.
func (mr *MockToolInstallerMockRecorder) InstallKEDA(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallKEDA", reflect.TypeOf((*MockToolInstaller)(nil).InstallKEDA), ctx)
}

// VerifyClusterSetup mocks base method.
func (m *MockToolInstaller) VerifyClusterSetup(ctx context.Context) (*common.ClusterInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyClusterSetup", ctx)
	ret0, _ := ret[0].(*common.ClusterInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyClusterSetup indicates an expected call of VerifyClusterSetup.
func (mr *MockToolInstallerMockRecorder) VerifyClusterSetup(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyClusterSetup", reflect.TypeOf((*MockToolInstaller)(nil).VerifyClusterSetup), ctx)
}
